name: Reusable deploy workflow


on:
  workflow_call:
    inputs:
      build_id:
        required: true
        type: number
        default: 100
      deploy_target:
        required: true
        type: string
        default: 'dev'
      perform_deploy:
        required: true
        type: boolean
        default: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ inputs.perform_deploy }}
    steps:
      - name: Deploy build to target
        run: echo "Deploying build:${{ fromJSON(inputs.build_id) }} to target:${{ inputs.deploy_target }}"
